import logging
import uuid

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import FileResponse
from sqlalchemy.orm import Session

from app.database.database import get_db
from app.database.models import User
from app.schemas.processing import ReportRequest, ReportResponse
from app.services.report_service import (
    delete_report,
    generate_report,
    get_report_path,
    list_reports,
)
from app.utils.auth import get_current_user

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/report", tags=["Reports"])


@router.post(
    "/generate",
    response_model=ReportResponse,
    summary="Generate a PDF report for a processing history record",
)
async def generate_report_endpoint(
    payload: ReportRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    try:
        result = generate_report(db, current_user, payload.history_id)
        return ReportResponse(
            report_url=result["report_url"],
            generated_at=result["generated_at"],
        )
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Report generation error: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to generate PDF report",
        )


@router.get(
    "/download/{filename}",
    summary="Download a generated PDF report",
)
async def download_report(
    filename: str,
):
    try:
        file_path = get_report_path(filename)
        return FileResponse(
            path=file_path,
            media_type="application/pdf",
            filename=filename,
            headers={"Content-Disposition": f'attachment; filename="{filename}"'},
        )
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Report download error: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to download report",
        )


@router.get(
    "/list",
    summary="List all reports generated by the current user",
)
async def list_user_reports(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    try:
        return list_reports(db, current_user)
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"List reports error: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to list reports",
        )


@router.delete(
    "/{report_id}",
    summary="Delete a generated report",
)
async def delete_report_endpoint(
    report_id: str,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    try:
        return delete_report(db, current_user, report_id)
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Delete report error: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to delete report",
        )
